#! /bin/bash
# This scipts is to setup the symbolic link

bash ~/dotfiles/requirments.sh

dotfiles="bashrc aliases zprofile yabairc skhdrc exports func extra \
    zshrc vimrc vim gitconfig gitignore_global gdbinit"
files="development"
vscode="keybindings settings"
vscodepath="$HOME/Library/Application Support/Code/User"

for file in $dotfiles; do
	[[ ! -L ~/."$file" ]] && ln -s ~/dotfiles/"$file" ~/."$file"
done

for file in $files; do
	[[ ! -f ~/"$file" ]] && ln -s ~/dotfiles/"$file" ~/"$file"
done

if [[ -e $vscodepath ]]; then
	for file in $vscode; do
		[[ ! -L "$vscodepath/$file".json ]] && ln -s ~/dotfiles/vscode/"$file".json "$vscodepath/$file".json
	done
fi

# we use oh my zsh
if [[ ! -d ~/.oh-my-zsh ]]; then
	cd || exit
	[[ -e ~/install.sh ]] || wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
	sh install.sh
else
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
	git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
	git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
	git clone --depth=1 https://github.com/unixorn/fzf-zsh-plugin.git "${ZSH_CUSTOM:-~/.oh-my-zsh/custom}"/plugins/fzf-zsh-plugin
	[[ -e ~/install.sh ]] && rm ~/install.sh
fi

# we use oh my tmux
if [[ ! -d ~/.tmux ]]; then
	cd || exit
	git clone https://github.com/gpakosz/.tmux.git
	ln -s -f .tmux/.tmux.conf .
	ln -s -f dotfiles/tmux.conf.local ./.tmux.conf.local
fi
