#! /bin/bash
# This scipts is to setup the symbolic link

# Install required packages
if [[ $(uname) == "Linux" ]]; then
	if [[ -n "$(command -v apt)" ]]; then
		sudo apt update
		for i in $(cat pkglist); do sudo apt-get install $i; done  # recommended
	elif [[ -n "$(command -v pacman)" ]]; then
		sudo pacman -Syu
		sudo pacman -S --needed --noconfirm - < pkglist
		pacman -S --needed - < pkglist
	else
		echo "Unsupported install command"
		exit 1
	fi
else
	echo "Unsuppored OS"
	exit 1
fi

stow -R git bash zsh i3 joshuto kitty npm skhd tmux vim vscode yabai

# we use oh my zsh
if [[ ! -d $HOME/.oh-my-zsh ]]; then
	cd || exit
	[[ -e $HOME/install.sh ]] || wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
	sh install.sh
else
	git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
	git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
	git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
	git clone --depth=1 https://github.com/unixorn/fzf-zsh-plugin.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/fzf-zsh-plugin
	git clone --depth=1 https://github.com/zsh-users/zsh-completions.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-completions
	[[ -e $HOME/install.sh ]] && rm $HOME/install.sh
fi

# we use oh my tmux
if [[ ! -d $HOME/.tmux ]]; then
	cd || exit
	git clone https://github.com/gpakosz/.tmux.git
	ln -s -f .tmux/.tmux.conf .
	ln -s -f dotfiles/tmux.conf.local ./.tmux.conf.local
fi
